// jQuery like selection of elements.
window.$ = document.querySelectorAll.bind(document);

// Changes for  Firefox
if (navigator.userAgent.match(/firefox/i)) {
    // Unicode font sizes
    let ffBtn = "font-weight: normal; font-size: 2em; margin-left: 0.3em;";
    $("#restart-symbol")[0].setAttribute("style", ffBtn);

    let ffwait = "line-height: 1em; font-size: 4em;";
    $(".waiting")[0].setAttribute("style", ffwait);
}

/////////////////////////////////////////

// Sorted list of the 500 most common English words.
let wordList = [
  "yang",
"dan",
"di",
"ini",
"untuk",
"mereka",
"kita",
"dari",
"adalah",
"tidak",
"itu",
"akan",
"dalam",
"bahwa",
"dengan",
"anda",
"ada",
"saya",
"pada",
"kami",
"ke",
"lebih",
"telah",
"seperti",
"planet",
"apa",
"satu",
"tahun",
"hal",
"tapi",
"bumi",
"besar",
"sangat",
"bisa",
"semua",
"mungkin",
"hanya",
"orang",
"memiliki",
"jika",
"sebuah",
"beberapa",
"atau",
"banyak",
"dunia",
"karena",
"menjadi",
"dapat",
"lain",
"benar",
"oleh",
"sebagai",
"bintang",
"melihat",
"aku",
"luar",
"alam",
"dia",
"tahu",
"hidup",
"jadi",
"apakah",
"manusia",
"sama",
"sekarang",
"datang",
"harus",
"bagaimana",
"hari",
"ketika",
"sini",
"narator",
"tempat",
"salah",
"membuat",
"sendiri",
"tentang",
"semesta",
"sistem",
"tetapi",
"mana",
"waktu",
"bulan",
"terjadi",
"paling",
"menemukan",
"pergi",
"kehidupan",
"baru",
"air",
"setiap",
"kecil",
"juga",
"sesuatu",
"cara",
"baik",
"bahkan",
"sekitar",
"kemudian",
"ia",
"kembali",
"jauh",
"matahari",
"seluruh",
"saat",
"surya",
"kuno",
"lalu",
"mulai",
"pernah",
"pertama",
"angkasa",
"ruang",
"begitu",
"selama",
"saja",
"makhluk",
"keluar",
"atas",
"cukup",
"tata",
"melakukan",
"energi",
"bawah",
"biasa",
"bagi",
"hampir",
"teknologi",
"sana",
"gravitasi",
"uang",
"ingin",
"lagi",
"pikir",
"sampai",
"mengapa",
"laut",
"setelah",
"secara",
"disebut",
"mengambil",
"sedikit",
"seorang",
"mengatakan",
"panas",
"namun",
"dua",
"melalui",
"asing",
"cahaya",
"bagian",
"bekerja",
"menarik",
"jenis",
"permukaan",
"ufo",
"antara",
"berpikir",
"ditemukan",
"masih",
"sudah",
"percaya",
"gas",
"masyarakat",
"kali",
"mendapatkan",
"bukan",
"aneh",
"penting",
"bentuk",
"teori",
"para",
"sumber",
"masalah",
"perjalanan",
"mars",
"langit",
"ilmuwan",
"kau",
"dekat",
"sebenarnya",
"nya",
"menggunakan",
"awal",
"amerika",
"berbeda",
"menciptakan",
"tanpa",
"juta",
"sehingga",
"berarti",
"menunjukkan",
"berada",
"tak",
"suatu",
"pesawat",
"bukti",
"pemerintah",
"tentu",
"kekuatan",
"mencari",
"miliar",
"masa",
"lakukan",
"jupiter",
"terus",
"udara",
"rumah",
"diri",
"lainnya",
"galaksi",
"kepada",
"daya",
"raksasa",
"ribuan",
"ya",
"memberikan",
"es",
"akhirnya",
"gambar",
"mesin",
"meskipun",
"tanah",
"mencoba",
"pertanyaan",
"alien",
"perlu",
"malam",
"lihat",
"lama",
"perang",
"tersebut",
"merupakan",
"jelas",
"sementara",
"akhir",
"terlalu",
"kuat",
"maka",
"batu",
"peradaban",
"tinggi",
"selalu",
"daripada",
"tampaknya",
"membawa",
"dingin",
"terbesar",
"punya",
"belum",
"sejarah",
"tetap",
"sebelum",
"lubang",
"sebagian",
"dibuat",
"alasan",
"mil",
"titik",
"cepat",
"terlihat",
"menghasilkan",
"proses",
"terbang",
"sedang",
"dasar",
"digunakan",
"penemuan",
"ilmiah",
"anak",
"muncul",
"turun",
"depan",
"jam",
"pengetahuan",
"gunung",
"atmosfer",
"dikenal",
"sekali",
"terakhir",
"bola",
"segala",
"perusahaan",
"luas",
"emas",
"bahan",
"membangun",
"pun",
"tengkorak",
"negara",
"berubah",
"ekonomi",
"siapa",
"selatan",
"the",
"tumbuh",
"jalan",
"tepat",
"tertentu",
"indah",
"jumlah",
"ilmu",
"tiga",
"abad",
"berbicara",
"berkembang",
"saturnus",
"hewan",
"kedua",
"awan",
"satunya",
"spesies",
"mengubah",
"panjang",
"mencapai",
"tujuan",
"bersama",
"membantu",
"tiba",
"hitam",
"ukuran",
"membentuk",
"orbit",
"moneter",
"semacam",
"hukum",
"suasana",
"cincin",
"kapal",
"kristal",
"cerita",
"sederhana",
"sejak",
"berkata",
"agama",
"tubuh",
"sempurna",
"tinggal",
"mampu",
"struktur",
"sosial",
"mata",
"kemungkinan",
"berjalan",
"suhu",
"musim",
"tanaman",
"pesan",
"ide",
"lingkungan",
"semuanya",
"merasa",
"dilakukan",
"radiasi",
"menurut",
"s",
"masuk",
"hidrogen",
"berikutnya",
"kerja",
"memahami",
"seseorang",
"tua",
"sebelumnya",
"informasi",
"mengorbit",
"demikian",
"dibangun",
"jatuh",
"semakin",
"daerah",
"menyebabkan",
"dimana",
"laki",
"penuh",
"maju",
"menakjubkan",
"dasarnya",
"jutaan",
"an",
"bank",
"empat",
"setengah",
"atom",
"kilometer",
"tim",
"masing",
"perubahan",
"pekerjaan",
"menghancurkan",
"tengah",
"cair",
"kondisi",
"cerdas",
"hilang",
"utama",
"merah",
"lima",
"memungkinkan",
"bergerak",
"teleskop",
"pusat",
"langsung",
"karbon",
"mati",
"lingkaran",
"umum",
"listrik",
"astronom",
"berat",
"tampak",
"berasal",
"gagasan",
"militer",
"terhadap",
"astronot",
"pasti",
"garis",
"penjelasan",
"wilayah",
"tsoukalos",
"sisi",
"a",
"et",
"bertahan",
"terletak",
"mesir",
"dimulai",
"einstein",
"gelombang",
"metode",
"berbagai",
"perilaku",
"radio",
"bahasa",
"muda",
"debu",
"belakang",
"kota",
"pikiran",
"rasa",
"ratusan",
"itulah",
"kesempatan",
"belajar",
"mengungkapkan",
"sulit",
"misteri",
"makanan",
"skala",
"hutan",
"kaki",
"tekanan",
"tanggal",
"piramida",
"mirip",
"tunggal",
"io",
"mudah",
"kepala",
"tingkat",
"gelap",
"komputer",
"misi",
"inggris",
"tangan",
"venus",
"dewa",
"fisika",
"burung",
"terbaik",
"yeah",
"massa",
"berapi",
"produk",
"sepuluh",
"sering",
"sinyal",
"apapun",
"berbasis",
"membayangkan",
"tanda",
"menjelaskan",
"meninggalkan",
"kurang",
"kenyataannya",
"badai",
"bang",
"nah",
"keuntungan",
"diambil",
"fakta",
"mengejutkan",
"terbuat",
"memberitahu",
"duduk",
"kontak",
"pemahaman",
"kasus",
"penampakan",
"birnes",
"voyager",
"membutuhkan",
"serikat",
"melakukannya",
"derajat",
"segera",
"khusus",
"ledakan",
"kosmos",
"oh",
"angin",
"zona",
"siap",
"otak",
"lautan",
"danau",
"mendapat",
"berputar",
"hujan",
"kata",
"gaya",
"kehilangan",
"jerman",
"kecepatan",
"super",
"diciptakan",
"arah",
"pria",
"posisi",
"menjaga",
"inti",
"mengerti",
"bagus",
"mengakui",
"memberi",
"berhenti",
"langkah",
"yakin",
"fenomena",
"lahir",
"alat",
"t",
"kekuasaan",
"senjata",
"bayangkan",
"berdiri",
"film",
"menerima",
"makan",
"mari",
"tuhan",
"hati",
"oke",
"menempatkan",
"tantangan",
"contoh",
"organisme",
"produksi",
"bunga",
"kasih",
"partikel",
"budaya",
"sepanjang",
"astronomi",
"jarak",
"nyata",
"keras",
"situs",
"industri",
"kebutuhan",
"keluarga",
"europa",
"suara",
"mendengar",
"dr",
"bencana",
"perempuan",
"laporan",
"padat",
"tenaga",
"berakhir",
"pencarian",
"setidaknya",
"as",
"kelompok",
"gerakan",
"pasang",
"menyadari",
"sumeria",
"kamera",
"pasifik",
"dihasilkan",
"memilih",
"kemampuan",
"menghabiskan",
"maksudku",
"utang",
"biru",
"terima",
"modern",
"mengirim",
"menyatakan",
"sifat",
"enam",
"proyek",
"warna",
"membaca",
"darwin",
"bertemu",
"mobil",
"nilai",
"naik",
"tersedia",
"tipis",
"berbahaya",
"diperlukan",
"buku",
"keajaiban",
"lanskap",
"besi",
"pandangan",
"pulau",
"menunggu",
"afrika",
"binatang",
"asteroid",
"meter",
"menit",
"hasil",
"operasi",
"berharap",
"keputusan",
"sepenuhnya",
"alkitab",
"berhasil",
"mendorong",
"mendalam",
"sepotong",
"berlangsung",
"persis",
"utara",
"mendengarkan",
"cuaca",
"pulsar",
"kebanyakan",
"ikan",
"memang",
"jepang",
"kristen",
"terbentuk",
"pantai",
"kawah",
"barang",
"penelitian",
"nenek",
"kompleks",
"puing",
"skeptis",
"inilah",
"keyakinan",
"dirancang",
"terpisah",
"sebut",
"pendapat",
"kecuali",
"yah",
"bidang",
"berharga",
"pola",
"molekul",
"presiden",
"allah",
"pertahanan",
"tujuh",
"berisi",
"kecelakaan",
"oksigen",
"serangga",
"dibutuhkan",
"jantung",
"moyang",
"sinar",
"efek",
"rumit",
"meningkatkan",
"per",
"meningkat",
"kepentingan",
"persamaan",
"kuantum",
"mengunjungi",
"memeriksa",
"bangsa",
"hubungan",
"siklus",
"titan",
"miliki",
"jawaban",
"terbuka",
"dolar",
"mengembangkan",
"paus",
"goldilocks",
"menyelesaikan",
"membuka",
"catatan",
"mengetahui",
"mendukung",
"kematian",
"nama",
"berlaku",
"misalnya",
"sendirian",
"keseluruhan",
"pribadi",
"sisa",
"teks",
"tindakan",
"melihatnya",
"acara",
"pohon",
"diperkirakan",
"global",
"rhea",
"kejadian",
"noory",
"maya",
"drake",
"menuju",
"sel",
"pengamatan",
"lanjut",
"puncak",
"dampak",
"kalau",
"jawab",
"penggunaan",
"seti",
"kenapa",
"umat",
"detik",
"hak",
"lambat",
"dennin",
"up",
"kosmik",
"termasuk",
"menggambarkan",
"jangan",
"ribu",
"foto",
"meledak",
"bertanya",
"cadangan",
"metana",
"big",
"petunjuk",
"membayar",
"intelijen",
"aman",
"man",
"bermain",
"berapa",
"kelangkaan",
"batuan",
"kepiting",
"howe",
"sejauh",
"nuklir",
"biaya",
"langka",
"selain",
"bebas",
"menyarankan",
"agak",
"mempertimbangkan",
"lapisan",
"api",
"bangunan",
"menyerang",
"dikonfirmasi",
"biasanya",
"kira",
"b",
"mekanika",
"macam",
"pinjaman",
"tulang",
"bakteri",
"misterius",
"geologi",
"milyar",
"berhubungan",
"sekitarnya",
"peristiwa",
"balik",
"limbah",
"kejahatan",
"peduli",
"buatan",
"kimia",
"kemajuan",
"dianggap",
"periode",
"hipotesis",
"mempertahankan",
"terkait",
"lembaga",
"angkatan",
"serangan",
"piring",
"karang",
"childress",
"kontrol",
"rahasia",
"kaya",
"heran",
"jaringan",
"cocok",
"sungai",
"delapan",
"miliaran",
"pengalaman",
"kanan",
"berita",
"mengganggu",
"desain",
"string",
"fisik",
"disebabkan",
"menerus",
"bersih",
"evolusi",
"genetik",
"terdekat",
"nasa",
"kepler",
"sejumlah",
"tabrakan",
"eropa",
"new",
"cenderung",
"kesalahan",
"dirinya",
"teknik",
"kecerdasan",
"kisah",
"dalamnya",
"wanita",
"olah",
"magnet",
"lemah",
"ellie",
"bertanggung",
"unik",
"fiksi",
"segalanya",
"teknis",
"berusaha",
"benua",
"runtuh",
"berdasarkan",
"ahli",
"beruntung",
"diameter",
"data",
"dibandingkan",
"kadang",
"memulai",
"diketahui",
"ancaman",
"muka",
"teman",
"ayah",
"disk",
"bulu",
"potongan",
"yo",
"katakan",
"benda",
"media",
"ulang",
"singkat",
"sebagainya",
"jawabannya",
"maksud",
"konsekuensi",
"kelimpahan",
"kunjungan",
"pembentukan",
"dikelilingi",
"satelit",
"menulis",
"helium",
"off",
"individu",
"batas",
"tidur",
"murni",
"harfiah",
"memutuskan",
"buruk",
"dapatkan",
"stasiun",
"perhatian",
"eh",
"menjawab",
"keuangan",
"total",
"bisnis",
"well",
"aturan",
"newton",
"surut",
"ton",
"kekerasan",
"bakar",
"temukan",
"mungkinkah",
"mengumpulkan",
"isiands",
"primata",
"dikunjungi",
"balon",
"hot",
"tertutup",
"minggu",
"juli",
"seberapa",
"musik",
"belanda",
"kiri",
"program",
"australia",
"akal",
"sebanyak",
"matematika",
"didasarkan",
"perbedaan",
"generasi",
"dikembangkan",
"mikroba",
"ii",
"e",
"selamat",
"takut",
"selanjutnya",
"membuatnya",
"tersisa",
"gurun",
"mengatur",
"setuju",
"terhitung",
"kehadiran",
"pemimpin",
"efisien",
"keberadaan",
"potensi",
"berinteraksi",
"ekstrim",
"gen",
"departemen",
"pertambangan",
"peru",
"kerajinan",
"peluru",
"berbatu",
"rendah",
"logam",
"jet",
"antena",
"huygens",
"senang",
"cairan",
"link",
"mekanisme",
"terutama",
"peran",
"ibu",
"kenal",
"bangun",
"it",
"menjalankan",
"canggih",
"berevolusi",
"ak",
"memecahkan",
"usia",
"memegang",
"tenggelam",
"ras",
"tertinggi",
"fosil",
"semut",
"kupu",
"bauval",
"orion",
"objek",
"beku"
];

//////////////////////////////////////////

// Knuth-Fisher-Yates Shuffle
// http://bost.ocks.org/mike/shuffle/
function shuffle(array) {
    let m = array.length, t, i;
    // While there remain elements to shuffle…
    while (m) {
        // Pick a remaining element…
        i = Math.floor(Math.random() * m--);
        // And swap it with the current element.
        t = array[m];
        array[m] = array[i];
        array[i] = t;
    }
    return array;
}

// Add words to word-section

function addWords() {
    // clear existing word-section
    let wordSection = $("#word-section")[0];
    wordSection.innerHTML = "";
    $("#typebox")[0].value = "";

    for (let i = 350; i > 0; i--) {
        let words = shuffle(wordList);
        let wordSpan = `<span>${words[i]}</span>`;
        wordSection.innerHTML += wordSpan;
    }
    // mark first word as current-word
    wordSection.firstChild.classList.add("current-word");

    // mark last word with magic-box
    // let magicBox = document.createElement("DIV");
    // magicBox.classList.add("magic-box");
    // wordSection.appendChild(magicBox);
}

//////////////////////////////////////////

// Word Colors
let colorCurrentWord =" #dddddd";
let colorCorrectWord = "#93C572";
let colorIncorrectWord = "#e50000";

// Word Count and other data.
let wordData = {
    seconds: 60,
    correct: 0,
    incorrect: 0,
    total: 0,
    typed: 0
};

//////////////////////////////////////////
// Initial implementation notes:
// next word on <space>, if empty, then set value=""
// after <space> if value == current-word, mark as correct-word
// else, mark as incorrect-word
// if value.length != current-word[:value.length], mark as incorrect-word
// else, mark as current-word
//////////////////////////////////////////

function checkWord(word) {
    let wlen = word.value.length;
    // how much we have of the current word.
    let current = $(".current-word")[0];
    let currentSubstring = current.innerHTML.substring(0, wlen);
    // check if we have any typing errors
    if (word.value.trim() != currentSubstring) {
        current.classList.add("incorrect-word-bg");
        return false;
    } else {
        current.classList.remove("incorrect-word-bg");
        return true;
    }
}

function submitWord(word) {
    // update current-word and
    // keep track of correct & incorrect words
    let current = $(".current-word")[0];

    if (checkWord(word)) {
        current.classList.remove("current-word");
        current.classList.add("correct-word-c");
        wordData.correct += 1;
    } else {
        current.classList.remove("current-word", "incorrect-word-bg");
        current.classList.add("incorrect-word-c");
        wordData.incorrect += 1;
    }
    // update wordData
    wordData.total = wordData.correct + wordData.incorrect;

    // make the next word the new current-word.
    current.nextSibling.classList.add("current-word");
}

function clearLine() {
    // remove past words once you get to the next line
    let wordSection = $("#word-section")[0];
    let current = $(".current-word")[0]; // second line (first word)
    let previous = current.previousSibling; // first line (last word)
    let children = $(".correct-word-c, .incorrect-word-c").length;

    // <span>'s on the next line have a greater offsetTop value
    // than those on the top line.
    // Remove words until the first word on the second line
    // is the fistChild of word-section.
    if (current.offsetTop > previous.offsetTop) {
        for (let i = 0; i < children; i++) {
            wordSection.removeChild(wordSection.firstChild);
        }
    }
}

function isTimer(seconds) {
    // BUG: page refresh with keyboard triggers onkeyup and starts timer
    // Use restart button to reset timer

    let time = seconds;
    // only set timer once
    let one = $("#timer > span")[0].innerHTML;
    if (one == "1:00") {
        let typingTimer = setInterval(() => {
            if (time <= 0) {
                clearInterval(typingTimer);
            } else {
                time -= 1;
                let timePad = (time < 10) ? ("0" + time) : time; // zero padded
                $("#timer > span")[0].innerHTML = `0:${timePad}`;
            }
        }, 1000);
    } else if (one == "0:00") {return false;}
    return true;
}

function calculateWPM(data) {
    let {seconds, correct, incorrect, total, typed} = data;
    let min = (seconds / 60);
    let wpm = Math.ceil((typed / 5) - (incorrect) / min);
    let accuracy = Math.ceil((correct / total) * 100);

    if (wpm < 0) {wpm = 0;}     // prevent negative wpm from incorrect words

    // template strings are pretty cool
    let results = `<ul id="results">
        <li>WPM: <span class="wpm-value">${wpm}</span></li>
        <li>Accuracy: <span class="wpm-value">${accuracy}%</span></li>
        <li id="results-stats">
        Total Words: <span>${total}</span> |
        Correct Words: <span>${correct}</span> |
        Incorrect Words: <span>${incorrect}</span> |
        Characters Typed: <span>${typed}</span>
        </li>
        </ul>`;

    $("#word-section")[0].innerHTML = results;

    // color code accuracy
    let wpmClass = $("li:nth-child(2) .wpm-value")[0].classList;
    if (accuracy > 80) {wpmClass.add("correct-word-c");}
    else { wpmClass.add("incorrect-word-c");}

    console.log(wordData);
}

function typingTest(e) {
    // Char:        Key Code:
    // <space>      32
    // <backspace>  8
    // <shift>      16
    // [A-Z]        65-90
    // [' "]        222

    // Get key code of current key pressed.
    e = e || window.event;
    let kcode = e.keyCode;
    let word = $("#typebox")[0];

    // check if empty (starts with space)
    if (word.value.match(/^\s/g)) {
        word.value = "";
    } else {
        // Only score when timer is on.
        if (isTimer(wordData.seconds)) {
            checkWord(word);    // checks for typing errors while you type
            // <space> submits words
            if (kcode == 32) {
                submitWord(word);  // keep track of correct / incorrect words
                clearLine();  // get rid of old words
                $("#typebox")[0].value = ""; // clear typebox after each word
            }
            wordData.typed += 1; // count each valid character typed
        }else {
            // Display typing test results.
            calculateWPM(wordData);
        }
    }
}

function restartTest() {
    $("#typebox")[0].value = "";
    location.reload();
}
